```{r}
#! /usr/bin/Rscript --no-init-file
# Dongdong Kong ----------------------------------------------------------------
# Copyright (c) 2025 Dongdong Kong. All rights reserved.
source("scripts/main_pkgs.R")

models <- c("m05_ihacres_7p_1s", "m07_gr4j_4p_2s", "m09_susannah1_6p_2s", "m28_xinanjiang_12p_4s", "XAJ")
model <- models[1]

load(glue("./OUTPUT/res_{model}.rda"))
```

```{r}
SITE <- "县河"
d <- res[[SITE]]$d_full
xgb <- res[[SITE]]$xgb
pred <- get_pred(xgb) #

c(data_obs, info_flood) %<-% flood_divide(d, SITE, extend = 3) # hydro
nrow <- ceiling(nrow(info_flood) / 4)
dat_obs <- data_obs[, .(group_name, time, P, Q_obs)]

LEAD <- "lead_04"
dat_sim <- melt_list(list(
  Hydro = pred$Hydro[, .(time, Q_sim)],
  HydroMetXGB = pred$HydroMetXGB[, .(time, Q_sim)],
  HydroMetQlagXGB = pred$HydroMetQlagXGB[lead == LEAD, .(time, Q_sim)]
), "model") %>% merge(dat_obs) %>% 
  mutate(model = factor(model, c("Hydro", "HydroMetXGB", "HydroMetQlagXGB")))


c(Q_min, Q_peak, q.max, prcp.max) %<-% get_config(SITE)
p <- plot_FloodEvents_Qsim_models(dat_obs, dat_sim, prcp.max, q.max)

write_fig(p, "b.svg", 12, 2.5 * nrow, show = FALSE)
```
