```{r}
# Copyright (c) 2025 Dongdong Kong. All rights reserved.
source('scripts/main_pkgs.R')
devtools::load_all()

# read output of ModernHydroModels
read_output <- function(indir) {
  fs <- dir2(indir, "Output.*.csv")
  map(fs, fread) %>% rbindlist()
}

sites <- c("松柏（二）", "县河", "房县", "延坝", "孤山")

root <- "/mnt/z/GitHub/jl-pkgs/ModernHydroModels.jl" %>% path.mnt()
# indir = glue("{dir_root}/Project_Shiyan2025/OUTPUT/version1_千里眼/")
dir_root <- glue("{root}/Project_Shiyan2025/OUTPUT/version3_洪水摘录表_OnlyEvents")
models <- dir(dir_root)

run_xgb <- function(model, overwrite=FALSE) {
  fout <- glue("./OUTPUT/res_{model}.rda")
  (isfile(fout) && !overwrite) && return()

  indir = glue("{dir_root}/{model}")
  df <- read_output(indir) %>% merge(forcing) # [site, time, P, Q_obs, Q_sim, PET_FAO98, PET_PT1972, PET_Romanenko]

  print(model)
  res <- map(seq_along(sites), function(i) {
    SITE = sites[i]
    fprintf("[%d] %s \n", i, SITE)

    d_full <- df[site == SITE, ] # %>% add_previous()
    xgb <- train_xgboost(d_full)
    info <- cal_pass_rate(xgb, d_full) # 合格率并未提升太多
    # c(info_pass, info_flood, gof) %<-% info
    listk(xgb, info)
  }) %>% set_names(sites)
  save(res, file = fout)
}

model = models[5]
SITE <- sites[1]
```

```{r}
f_forcing <- glue("{root}/apps/data/十堰_Forcing_hourly_ALL_v20260417_basins24.csv")
forcing <- fread(f_forcing) %>% select(-Q, -R, -Z, -area_km2, -Tair) # 仅使用气象数据

run_xgb(models[5], overwrite = TRUE)
# map(models, run_xgb)
```
