```{r}
pacman::p_load(
  Ipaper, data.table, dplyr, lubridate, 
  kfold, zeallot, 
  ggplot2, gg.layers
)
devtools::load_all(".")
devtools::load_all("Z:/GitHub/cug-hydro/kfold.R")
options(datatable.print.nrow = 20)

sites = c("松柏（二）", "县河", "房县", "延坝", "孤山")
SITE = sites[5]
```

```{r}
dir_root = "Z:/GitHub/jl-pkgs/ModernHydroModels.jl"

f_forcing = glue("{dir_root}/apps/data/十堰_Forcing_hourly_ALL_v20260417_basins24.csv")
forcing = fread(f_forcing)
# outdir = glue("{dir_root}/Project_Shiyan2025/OUTPUT/version1_千里眼/")
```

```{r}
read_dir <- function(indir) {
  fs = dir2(indir, "Output.*.csv")
  map(fs, fread) %>% rbindlist()
}

indir <- glue("{dir_root}/Project_Shiyan2025/OUTPUT/version3_洪水摘录表_OnlyEvents")
df = read_dir(indir) %>% merge(forcing) 

Qt = previous_tn(df$Q_obs, 12) %>% as.data.table() %>% 
  rename_with(\(x) paste0("Q_", x)) 
vars_Q <- names(Qt)[-1]

df = cbind(df[, .(site, time, Q_obs, Q_sim, Q, R,
  P, PET_FAO98, PET_PT1972, PET_Romanenko, Tair)], Qt)
```

```{r}
SITE <- sites[5]
d_full = df[site == SITE, ]
# d <- d_full[!is.na(Q_obs), ]
# Y <- select(d, Q_obs)
# X = select(d, P, PET = PET_Romanenko, all_of(vars_Q[1]), Q_sim)
# X = select(d, P, PET = PET_Romanenko, Q_sim)
```

```{r}
# r = xgboost(X, Y, early_stopping_rounds = 20)
r = kfold_xgboost(X, Y, nrounds = 200, early_stopping_rounds = 20, 
  # learning_rate = 0.1,
  max_depth = 3, min_child_weight = 10, subsample = 1)
```

## xgboost实战
```{r}
sites = c("松柏（二）", "县河", "房县", "延坝", "孤山")
SITE <- sites[1]

d_full <- df[site == SITE, ]
res = train_xgboost(d_full)

c(info_pass, info_flood) %<-% cal_pass_rate(res, d_full) # 合格率并未提升太多
info_pass
```

## debug
```{r}

```

> 统计每个结果
```{r}
d_gof = map(res, "gof") %>% melt_list("lead") %>% 
  mutate(lead = as.integer(lead))

p <- ggplot(d_gof[kfold == "all"], aes(lead, NSE)) + 
  geom_line() + 
  facet_wrap(~type, scales = "free") + 
  scale_x_continuous(breaks = seq(0, 12, 2))
write_fig(p, 'd:/Rplot.pdf', 10, 5)
```

## 检验洪水合格率

```{r}
```



```{r}
dtrain <- xgb.DMatrix(data = as.matrix(X), label = as.matrix(Y))
folds_list = chunk_stratified(unlist(Y))

cv <- xgb.cv(
  params = list(eta = 0.05, max_depth = 3, eval_metric = "rmse"),
  folds = folds_list,
  data = dtrain,
  nrounds = 1000,
  # nfold = 5,
  early_stopping_rounds = 20,
  verbose = 0
)

# cv$best_iteration
str(cv$early_stop)
```

## 
```{r}
d[, GOF(Q_obs, `Q_t-1`)]
```

## plot floods

```{r}
config_all = yaml::read_yaml("Z:/GitHub/jl-pkgs/ModernHydroModels.jl/Project_Shiyan2025/config_flood_events_十堰.yaml")
c(data, info_flood) %<-% flood_divide(d_full, config_all, SITE)
print(info_flood)
```

```{r}
info = data[, eval_Qmax(Q_obs, Q_sim), .(group_name)]
info[passed == TRUE, ]
```

## xgboost
```{r}
d[!is.na(Q_obs), GOF(Q_obs, `Q_t-1`)]
d[!is.na(Q_obs), GOF(Q_obs, `Q_t-2`)]

dat = select(d, starts_with("Q_t"))
cor(dat, use = "pairwise.complete.obs")
```
