```{r}
pacman::p_load(
  Ipaper, data.table, dplyr, lubridate, stringr,
  kfold, zeallot,
  ggplot2, gg.layers, ggrepel, ggh4x
)
# InitCluster(6)

devtools::load_all(".")
# devtools::load_all(path.mnt("/mnt/z/GitHub/cug-hydro/kfold.R"))
options(datatable.print.nrow = 20)

dir_root <- "/mnt/z/GitHub/jl-pkgs/ModernHydroModels.jl" %>% path.mnt()

sites <- c("松柏（二）", "县河", "房县", "延坝", "孤山")
SITE <- sites[5]
```

```{r}
f_forcing <- glue("{dir_root}/apps/data/十堰_Forcing_hourly_ALL_v20260417_basins24.csv")
forcing <- fread(f_forcing)
# outdir = glue("{dir_root}/Project_Shiyan2025/OUTPUT/version1_千里眼/")
```

```{r}
read_dir <- function(indir) {
  fs <- dir2(indir, "Output.*.csv")
  map(fs, fread) %>% rbindlist()
}

indir <- glue("{dir_root}/Project_Shiyan2025/OUTPUT/version3_洪水摘录表_OnlyEvents")
df <- read_dir(indir) %>% merge(forcing)

Qt <- previous_tn(df$Q_obs, 12) %>%
  as.data.table() %>%
  rename_with(\(x) paste0("Q_", x))
vars_Q <- names(Qt)[-1]

df <- cbind(df[, .(
  site, time, Q_obs, Q_sim, Q, R,
  P, PET_FAO98, PET_PT1972, PET_Romanenko, Tair
)], Qt)
```

## xgboost实战
```{r}
sites <- c("松柏（二）", "县河", "房县", "延坝", "孤山") %>% set_names(., .)

res <- foreach(SITE = sites, i = icount()) %do% {
  fprintf("[%d] %s \n", i, SITE)

  d_full <- df[site == SITE, ]
  res_xgb <- train_xgboost(d_full)
  info <- cal_pass_rate(res_xgb, d_full) # 合格率并未提升太多
  # c(info_pass, info_flood, gof) %<-% info
  info
}

save(res, file = "res.rda")
```
